[workspace]
members = [
    "policy-controller",
    "policy-controller/core",
    "policy-controller/grpc",
    "policy-controller/k8s/api",
    "policy-controller/k8s/index",
    "policy-test",
]
exclude = ["cni-plugin/linkerd-cni-validation"]

[profile.release]
lto = true
