{{if .Values.gateway.enabled -}}
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  {{ include "partials.namespace" . }}
  name: linkerd-gateway
  labels:
    linkerd.io/extension: multicluster
    app: {{.Values.gateway.name}}
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.gateway.name}}
  port: linkerd-proxy
---
apiVersion: policy.linkerd.io/v1beta1
kind: AuthorizationPolicy
metadata:
  {{ include "partials.namespace" . }}
  name: linkerd-gateway-clients
  labels:
    linkerd.io/extension: multicluster
    app: {{.Values.gateway.name}}
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  targetRef:
  - group: policy.linkerd.io
    kind: Server
    name: linkerd-gateway
  requiredAuthenticationRefs:
  # This policy permits access from all authenticated clients. This can be
  # further restricted by adding a `NetworkAuthentication` requirement that
  # enumerates the IP networks of remote source clusters.
  - group: policy.linkerd.io
    kind: MeshTLSAuthentication
    name: linkerd-gateway-clients
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthenication
metadata:
  {{ include "partials.namespace" . }}
  name: linkerd-gateway-clients
spec:
  # This can be further restricted by including explicit identity domain
  # suffixes instead of permitting all authenticated clients.
  identities: ["*"]
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  {{ include "partials.namespace" . }}
  name: linkerd-gateway-proxy-admin
  labels:
    linkerd.io/extension: multicluster
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.gateway.name}}
  port: linkerd-admin
---
apiVersion: policy.linkerd.io/v1beta1
kind: AuthorizationPolicy
metadata:
  {{ include "partials.namespace" . }}
  name: linkerd-gateway-proxy-admin-kubelet
  labels:
    linkerd.io/extension: multicluster
    app: {{.Values.gateway.name}}
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: linkerd-gateway-proxy-admin-kubelet
  requiredAuthenticationRefs:
  - group: policy.linkerd.io
    kind: NetworkAuthentication
    name: kubelet
 ---
apiVersion: policy.linkerd.io/v1beta1
kind: AuthorizationPolicy
metadata:
  {{ include "partials.namespace" . }}
  name: linkerd-gateway-probe
  labels:
    linkerd.io/extension: multicluster
    app: {{.Values.gateway.name}}
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: linkerd-gateway-proxy-admin
  requiredAuthenticationRefs:
  # This policy permits access from all authenticated clients. This can be
  # further restricted by adding a `NetworkAuthentication` requirement that
  # enumerates the IP networks of remote source clusters.
  - group: policy.linkerd.io
    kind: MeshTLSAuthentication
    name: linkerd-gateway-probe-clients
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthenication
metadata:
  {{ include "partials.namespace" . }}
  name: linkerd-gateway-probe-clients
spec:
  # This can be further restricted by including explicit identities of each
  # service mirror permitted probe this gateway.
  identities: ["*"]
{{end -}}
