
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  {{ include "partials.namespace" . }}
  name: service-mirror-proxy-admin
  labels:
    linkerd.io/extension: multicluster
spec:
  podSelector:
    matchLabels:
      component: linkerd-service-mirror
  port: linkerd-admin
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  {{ include "partials.namespace" . }}
  name: service-mirror-proxy-admin
  labels:
    linkerd.io/extension: multicluster
spec:
  server:
    name: service-mirror-proxy-admin
  client:
    # for kubelet probes
    unauthenticated: true
