---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  {{ include "partials.namespace" . }}
  name: service-mirror-admin
  labels:
    component: linkerd-service-mirror
spec:
  podSelector:
    matchLabels:
      component: linkerd-service-mirror
  port: admin-http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  {{ include "partials.namespace" . }}
  name: service-mirror-admin-prometheus
  labels:
    component: linkerd-service-mirror
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: service-mirror-admin
  requiredAuthenticationRefs:
  - group: policy.linkerd.io
    kind: MeshTLSAuthentication
    linkerd-viz: prometheus
    name: prometheus
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  {{ include "partials.namespace" . }}
  name: service-mirror-proxy-admin
  labels:
    linkerd.io/extension: multicluster
spec:
  podSelector:
    matchLabels:
      component: linkerd-service-mirror
  port: linkerd-admin
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  {{ include "partials.namespace" . }}
  name: service-mirror-proxy-admin-kubelet
  labels:
    component: linkerd-service-mirror
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: service-mirror-proxy-admin
  requiredAuthenticationRefs:
  - group: policy.linkerd.io
    kind: MeshTLSAuthentication
    name: kubelet
